
SOURCEFILES=mpg123d.cpp settings.cpp debugger.cpp misc.cpp mpg123.cpp udpserver.cpp mp3info.cpp playlist.cpp
LIBS=-pthread -lgnugetopt
LIBPATH=-L/usr/local/lib/
INCLUDE=-I/usr/local/include/

mpg123d:
	gcc -O $(SOURCEFILES) $(LIBS) $(INCLUDE) $(LIBPATH) -o mpg123d

clean:
	rm -f mpg123d


